version: '3'
services:
  postgresql:
      image: postgres:15
      container_name: wfc_postgresql
      healthcheck:
        test: ['CMD', 'pg_isready', '--user', 'dedp_test', '-d', 'dedp']
      environment:
        - POSTGRES_USER=wfc_test
        - POSTGRES_PASSWORD=wfc_test
        - POSTGRES_DB=wfc
      ports:
          - "5432:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
